name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies and build
        run: |
          pnpm i
          pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
